version: '3.7'

services:
  mysql:
    container_name: adm_beer_mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=adm_beer
    security_opt:
      - seccomp:unconfined
    ports:
      - "3306:3306"
    networks:
      - adm_beer_network

networks:
  adm_beer_network: